In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer

In [51]:
sentences = ['I Love My Dog',
            'I Love My Cat',
            'i love my cat and dog']

In [52]:
tokenizer = Tokenizer(num_words = 100, oov_token = '<oov>')
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index
print(word_index)

{'<oov>': 1, 'i': 2, 'love': 3, 'my': 4, 'dog': 5, 'cat': 6, 'and': 7}


In [53]:
sentences[0][1]

' '

# Generally texts should be in sequences, so will convert it to sequences

In [54]:
sequences = tokenizer.texts_to_sequences(sentences)

In [55]:
print(sequences)

[[2, 3, 4, 5], [2, 3, 4, 6], [2, 3, 4, 6, 7, 5]]


# Sequences of texts should be in same order(length) as we train neural netwroks with Images


In [59]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [60]:
padded = pad_sequences(sequences)

In [61]:
print(padded)

[[0 0 2 3 4 5]
 [0 0 2 3 4 6]
 [2 3 4 6 7 5]]


# Padding is done at the begining by adding zeroes defalut, however we can specify it also


In [62]:
padded = pad_sequences(sequences, maxlen = 10)

In [63]:
print(padded)

[[0 0 0 0 0 0 2 3 4 5]
 [0 0 0 0 0 0 2 3 4 6]
 [0 0 0 0 2 3 4 6 7 5]]


In [64]:
!wget https://scholar.google.com/citations?view_op=list_works&hl=en&user=EN3OcMsAAAAJ#d=gs_md_cita-d&u=%2Fcitations%3Fview_op%3Dview_citation%26hl%3Den%26user%3DEN3OcMsAAAAJ%26citation_for_view%3DEN3OcMsAAAAJ%3AqjMakFHDy7sC%26tzom%3D420

'wget' is not recognized as an internal or external command,
operable program or batch file.
'hl' is not recognized as an internal or external command,
operable program or batch file.
'user' is not recognized as an internal or external command,
operable program or batch file.
'u' is not recognized as an internal or external command,
operable program or batch file.


In [65]:
import json

# IMDB Review dataset



In [67]:
!pip install -q tensorflow-datasets


In [68]:
import tensorflow_datasets as tfds


In [ ]:
imdb, info = tfds.load("imdb_reviews", with_info = True, as_supervised = True)

Shuffling and writing examples to C:\Users\SINCHANA\tensorflow_datasets\imdb_reviews\plain_text\1.0.0.incompleteOQITIT\imdb_reviews-train.tfrecord


Shuffling and writing examples to C:\Users\SINCHANA\tensorflow_datasets\imdb_reviews\plain_text\1.0.0.incompleteOQITIT\imdb_reviews-test.tfrecord


In [ ]:
import numpy as np

In [ ]:
train, test = imdb['train'], imdb['test']